# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/brotter/anita16/components/AnitaAnalysisFramework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/brotter/anita16/components/AnitaAnalysisFramework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/brotter/anita16/components/AnitaAnalysisFramework/CMakeFiles /Users/brotter/anita16/components/AnitaAnalysisFramework/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/brotter/anita16/components/AnitaAnalysisFramework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named G__AnitaAnalysis.pcm

# Build rule for target.
G__AnitaAnalysis.pcm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 G__AnitaAnalysis.pcm
.PHONY : G__AnitaAnalysis.pcm

# fast build rule for target.
G__AnitaAnalysis.pcm/fast:
	$(MAKE) -f CMakeFiles/G__AnitaAnalysis.pcm.dir/build.make CMakeFiles/G__AnitaAnalysis.pcm.dir/build
.PHONY : G__AnitaAnalysis.pcm/fast

#=============================================================================
# Target rules for targets named AnitaAnalysis

# Build rule for target.
AnitaAnalysis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AnitaAnalysis
.PHONY : AnitaAnalysis

# fast build rule for target.
AnitaAnalysis/fast:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/build
.PHONY : AnitaAnalysis/fast

G__AnitaAnalysis.o: G__AnitaAnalysis.cxx.o

.PHONY : G__AnitaAnalysis.o

# target to build an object file
G__AnitaAnalysis.cxx.o:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/G__AnitaAnalysis.cxx.o
.PHONY : G__AnitaAnalysis.cxx.o

G__AnitaAnalysis.i: G__AnitaAnalysis.cxx.i

.PHONY : G__AnitaAnalysis.i

# target to preprocess a source file
G__AnitaAnalysis.cxx.i:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/G__AnitaAnalysis.cxx.i
.PHONY : G__AnitaAnalysis.cxx.i

G__AnitaAnalysis.s: G__AnitaAnalysis.cxx.s

.PHONY : G__AnitaAnalysis.s

# target to generate assembly for a file
G__AnitaAnalysis.cxx.s:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/G__AnitaAnalysis.cxx.s
.PHONY : G__AnitaAnalysis.cxx.s

src/AnalysisWaveform.o: src/AnalysisWaveform.cc.o

.PHONY : src/AnalysisWaveform.o

# target to build an object file
src/AnalysisWaveform.cc.o:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/AnalysisWaveform.cc.o
.PHONY : src/AnalysisWaveform.cc.o

src/AnalysisWaveform.i: src/AnalysisWaveform.cc.i

.PHONY : src/AnalysisWaveform.i

# target to preprocess a source file
src/AnalysisWaveform.cc.i:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/AnalysisWaveform.cc.i
.PHONY : src/AnalysisWaveform.cc.i

src/AnalysisWaveform.s: src/AnalysisWaveform.cc.s

.PHONY : src/AnalysisWaveform.s

# target to generate assembly for a file
src/AnalysisWaveform.cc.s:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/AnalysisWaveform.cc.s
.PHONY : src/AnalysisWaveform.cc.s

src/AnitaEventSummary.o: src/AnitaEventSummary.cc.o

.PHONY : src/AnitaEventSummary.o

# target to build an object file
src/AnitaEventSummary.cc.o:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/AnitaEventSummary.cc.o
.PHONY : src/AnitaEventSummary.cc.o

src/AnitaEventSummary.i: src/AnitaEventSummary.cc.i

.PHONY : src/AnitaEventSummary.i

# target to preprocess a source file
src/AnitaEventSummary.cc.i:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/AnitaEventSummary.cc.i
.PHONY : src/AnitaEventSummary.cc.i

src/AnitaEventSummary.s: src/AnitaEventSummary.cc.s

.PHONY : src/AnitaEventSummary.s

# target to generate assembly for a file
src/AnitaEventSummary.cc.s:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/AnitaEventSummary.cc.s
.PHONY : src/AnitaEventSummary.cc.s

src/AnitaTMVA.o: src/AnitaTMVA.cc.o

.PHONY : src/AnitaTMVA.o

# target to build an object file
src/AnitaTMVA.cc.o:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/AnitaTMVA.cc.o
.PHONY : src/AnitaTMVA.cc.o

src/AnitaTMVA.i: src/AnitaTMVA.cc.i

.PHONY : src/AnitaTMVA.i

# target to preprocess a source file
src/AnitaTMVA.cc.i:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/AnitaTMVA.cc.i
.PHONY : src/AnitaTMVA.cc.i

src/AnitaTMVA.s: src/AnitaTMVA.cc.s

.PHONY : src/AnitaTMVA.s

# target to generate assembly for a file
src/AnitaTMVA.cc.s:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/AnitaTMVA.cc.s
.PHONY : src/AnitaTMVA.cc.s

src/BasicFilters.o: src/BasicFilters.cc.o

.PHONY : src/BasicFilters.o

# target to build an object file
src/BasicFilters.cc.o:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/BasicFilters.cc.o
.PHONY : src/BasicFilters.cc.o

src/BasicFilters.i: src/BasicFilters.cc.i

.PHONY : src/BasicFilters.i

# target to preprocess a source file
src/BasicFilters.cc.i:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/BasicFilters.cc.i
.PHONY : src/BasicFilters.cc.i

src/BasicFilters.s: src/BasicFilters.cc.s

.PHONY : src/BasicFilters.s

# target to generate assembly for a file
src/BasicFilters.cc.s:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/BasicFilters.cc.s
.PHONY : src/BasicFilters.cc.s

src/FilterOperation.o: src/FilterOperation.cc.o

.PHONY : src/FilterOperation.o

# target to build an object file
src/FilterOperation.cc.o:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/FilterOperation.cc.o
.PHONY : src/FilterOperation.cc.o

src/FilterOperation.i: src/FilterOperation.cc.i

.PHONY : src/FilterOperation.i

# target to preprocess a source file
src/FilterOperation.cc.i:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/FilterOperation.cc.i
.PHONY : src/FilterOperation.cc.i

src/FilterOperation.s: src/FilterOperation.cc.s

.PHONY : src/FilterOperation.s

# target to generate assembly for a file
src/FilterOperation.cc.s:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/FilterOperation.cc.s
.PHONY : src/FilterOperation.cc.s

src/FilterStrategy.o: src/FilterStrategy.cc.o

.PHONY : src/FilterStrategy.o

# target to build an object file
src/FilterStrategy.cc.o:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/FilterStrategy.cc.o
.PHONY : src/FilterStrategy.cc.o

src/FilterStrategy.i: src/FilterStrategy.cc.i

.PHONY : src/FilterStrategy.i

# target to preprocess a source file
src/FilterStrategy.cc.i:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/FilterStrategy.cc.i
.PHONY : src/FilterStrategy.cc.i

src/FilterStrategy.s: src/FilterStrategy.cc.s

.PHONY : src/FilterStrategy.s

# target to generate assembly for a file
src/FilterStrategy.cc.s:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/FilterStrategy.cc.s
.PHONY : src/FilterStrategy.cc.s

src/FilteredAnitaEvent.o: src/FilteredAnitaEvent.cc.o

.PHONY : src/FilteredAnitaEvent.o

# target to build an object file
src/FilteredAnitaEvent.cc.o:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/FilteredAnitaEvent.cc.o
.PHONY : src/FilteredAnitaEvent.cc.o

src/FilteredAnitaEvent.i: src/FilteredAnitaEvent.cc.i

.PHONY : src/FilteredAnitaEvent.i

# target to preprocess a source file
src/FilteredAnitaEvent.cc.i:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/FilteredAnitaEvent.cc.i
.PHONY : src/FilteredAnitaEvent.cc.i

src/FilteredAnitaEvent.s: src/FilteredAnitaEvent.cc.s

.PHONY : src/FilteredAnitaEvent.s

# target to generate assembly for a file
src/FilteredAnitaEvent.cc.s:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/FilteredAnitaEvent.cc.s
.PHONY : src/FilteredAnitaEvent.cc.s

src/TGraphAligned.o: src/TGraphAligned.cc.o

.PHONY : src/TGraphAligned.o

# target to build an object file
src/TGraphAligned.cc.o:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/TGraphAligned.cc.o
.PHONY : src/TGraphAligned.cc.o

src/TGraphAligned.i: src/TGraphAligned.cc.i

.PHONY : src/TGraphAligned.i

# target to preprocess a source file
src/TGraphAligned.cc.i:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/TGraphAligned.cc.i
.PHONY : src/TGraphAligned.cc.i

src/TGraphAligned.s: src/TGraphAligned.cc.s

.PHONY : src/TGraphAligned.s

# target to generate assembly for a file
src/TGraphAligned.cc.s:
	$(MAKE) -f CMakeFiles/AnitaAnalysis.dir/build.make CMakeFiles/AnitaAnalysis.dir/src/TGraphAligned.cc.s
.PHONY : src/TGraphAligned.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... G__AnitaAnalysis.pcm"
	@echo "... install/local"
	@echo "... AnitaAnalysis"
	@echo "... G__AnitaAnalysis.o"
	@echo "... G__AnitaAnalysis.i"
	@echo "... G__AnitaAnalysis.s"
	@echo "... src/AnalysisWaveform.o"
	@echo "... src/AnalysisWaveform.i"
	@echo "... src/AnalysisWaveform.s"
	@echo "... src/AnitaEventSummary.o"
	@echo "... src/AnitaEventSummary.i"
	@echo "... src/AnitaEventSummary.s"
	@echo "... src/AnitaTMVA.o"
	@echo "... src/AnitaTMVA.i"
	@echo "... src/AnitaTMVA.s"
	@echo "... src/BasicFilters.o"
	@echo "... src/BasicFilters.i"
	@echo "... src/BasicFilters.s"
	@echo "... src/FilterOperation.o"
	@echo "... src/FilterOperation.i"
	@echo "... src/FilterOperation.s"
	@echo "... src/FilterStrategy.o"
	@echo "... src/FilterStrategy.i"
	@echo "... src/FilterStrategy.s"
	@echo "... src/FilteredAnitaEvent.o"
	@echo "... src/FilteredAnitaEvent.i"
	@echo "... src/FilteredAnitaEvent.s"
	@echo "... src/TGraphAligned.o"
	@echo "... src/TGraphAligned.i"
	@echo "... src/TGraphAligned.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

