### Separated out configuration options  #### 

###### Begin Compilation Options #######

### Override the compiler here (might be helpful on older Macs or testing with multiple compilers) 
#CXX=clang++

#####Site Specific  Flags (adjust to local site)
DLLSUF = ${DllSuf}
OBJSUF = ${ObjSuf}

ifndef ANITA_UTIL_INSTALL_DIR
ANITA_UTIL_INSTALL_DIR=/usr/local/ 
endif


