### Separated out configuration options  #### 

###### Begin Compilation Options #######

### Override the compiler here (might be helpful on older Macs or testing with multiple compilers) 
#CXX=clang++


### march=native might enable more optimizations
CXXFLAGS += -march=native 


### Comment out next two lines to disable explicit vectorization 
CXXFLAGS += -I$(VECTORDIR) -DENABLE_VECTORIZE $(ARCH_STRING)
VECTORIZE=$(VECTORDIR) 

### For Agner Fog's vectorclass, g++ needs to use -fabi-version=0 , but clang doesn't support this option. This is likely irrelevant if vectorization not enabled 
ifeq ($(CXX),g++)
CXXFLAGS+=-fabi-version=0 
endif



### Enable OpenMP support 
CXXFLAGS+= -fopenmp -DUSE_OMP
LDFLAGS += -fopenmp

#####Site Specific  Flags (adjust to local site)
DLLSUF = ${DllSuf}
OBJSUF = ${ObjSuf}

ifndef ANITA_UTIL_INSTALL_DIR
ANITA_UTIL_INSTALL_DIR=/usr/local/ 
endif


